workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      vars:
        XCODE_WORKSPACE: "mydshop-app/ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 18
      xcode: latest
      cocoapods: default

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true

    scripts:
      - name: Install dependencies
        script: |
          cd mydshop-app
          npm ci --legacy-peer-deps
          
      - name: Build web assets
        script: |
          cd mydshop-app
          npm run build
          
      - name: Update Capacitor
        script: |
          cd mydshop-app
          npx cap sync ios
          
      - name: Install CocoaPods
        script: |
          cd mydshop-app/ios/App
          pod install
          
      - name: Build iOS app
        script: |
          cd mydshop-app
          xcodebuild -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -destination 'generic/platform=iOS Simulator' \
            -derivedDataPath build/ios \
            build

    artifacts:
      - mydshop-app/build/ios/**/*.app
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - contato@mydshop.com.br
        notify:
          success: true
          failure: true

  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      vars:
        PACKAGE_NAME: "com.mydshop.app"
      node: 18
      java: 17

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: master
          include: true

    scripts:
      - name: Install dependencies
        script: |
          cd mydshop-app
          npm ci --legacy-peer-deps
          
      - name: Build web assets
        script: |
          cd mydshop-app
          npm run build
          
      - name: Update Capacitor
        script: |
          cd mydshop-app
          npx cap sync android
          
      - name: Build Android APK
        script: |
          cd mydshop-app/android
          chmod +x gradlew
          ./gradlew assembleDebug

    artifacts:
      - mydshop-app/android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - contato@mydshop.com.br
        notify:
          success: true
          failure: true
