workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.mydshop.app
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 18
      xcode: latest
      cocoapods: default

    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
        - pattern: develop
          include: true

    scripts:
      - name: Install dependencies
        script: |
          npm ci
          
      - name: Build web assets
        script: |
          npm run build
          
      - name: Update Capacitor
        script: |
          npx cap sync ios
          
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
          
      - name: Set up code signing
        script: |
          xcode-project use-profiles
          
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - seu-email@exemplo.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true

  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      android_signing:
        - mydshop_keystore
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.mydshop.app"
      node: 18
      java: 17

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - name: Install dependencies
        script: |
          npm ci
          
      - name: Build web assets
        script: |
          npm run build
          
      - name: Update Capacitor
        script: |
          npx cap sync android
          
      - name: Build Android APK/AAB
        script: |
          cd android
          ./gradlew assembleRelease
          ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - seu-email@exemplo.com
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
