-- CreateTable
CREATE TABLE IF NOT EXISTS `invoice` (
    `id` VARCHAR(191) NOT NULL,
    `orderId` VARCHAR(191) NOT NULL,
    `invoiceNumber` VARCHAR(191) NULL,
    `accessKey` VARCHAR(191) NULL,
    `series` VARCHAR(191) NULL,
    `type` ENUM('ADMIN', 'SELLER') NOT NULL,
    `status` ENUM('PENDING', 'PROCESSING', 'ISSUED', 'CANCELLED', 'ERROR') NOT NULL DEFAULT 'PENDING',
    `issuedBy` VARCHAR(191) NULL,
    `issuedAt` DATETIME(3) NULL,
    `cancelledAt` DATETIME(3) NULL,
    `cancelReason` TEXT NULL,
    `xmlUrl` VARCHAR(191) NULL,
    `pdfUrl` VARCHAR(191) NULL,
    `danfeUrl` VARCHAR(191) NULL,
    `cfop` VARCHAR(191) NULL,
    `naturezaOperacao` VARCHAR(191) NULL,
    `emitenteCnpj` VARCHAR(191) NULL,
    `emitenteNome` VARCHAR(191) NULL,
    `destinatarioCpf` VARCHAR(191) NULL,
    `destinatarioCnpj` VARCHAR(191) NULL,
    `destinatarioNome` VARCHAR(191) NULL,
    `valorTotal` DOUBLE NOT NULL,
    `valorProdutos` DOUBLE NOT NULL,
    `valorFrete` DOUBLE NULL,
    `valorDesconto` DOUBLE NULL,
    `valorIcms` DOUBLE NULL,
    `valorIpi` DOUBLE NULL,
    `valorPis` DOUBLE NULL,
    `valorCofins` DOUBLE NULL,
    `protocol` VARCHAR(191) NULL,
    `externalId` VARCHAR(191) NULL,
    `externalProvider` VARCHAR(191) NULL,
    `errorMessage` TEXT NULL,
    `metadata` LONGTEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `invoice_invoiceNumber_key`(`invoiceNumber`),
    UNIQUE INDEX `invoice_accessKey_key`(`accessKey`),
    INDEX `invoice_orderId_idx`(`orderId`),
    INDEX `invoice_status_idx`(`status`),
    INDEX `invoice_type_idx`(`type`),
    INDEX `invoice_issuedAt_idx`(`issuedAt`),
    INDEX `invoice_createdAt_idx`(`createdAt`),
    INDEX `invoice_invoiceNumber_idx`(`invoiceNumber`),
    INDEX `invoice_accessKey_idx`(`accessKey`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `invoice` ADD CONSTRAINT `invoice_orderId_fkey` FOREIGN KEY (`orderId`) REFERENCES `order`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
